"""
Option 19 - page skew / rotation detection.

Scans almost always have some skew (~1-3 degrees) because the paper
wasn't perfectly aligned on the platen or in the auto-feed. Natively
authored PDFs have perfectly horizontal text rows. So:

  detected skew angle  ->  classification
  ---------------------    -------------------
    < 0.3 degrees           native (rows are dead flat)
    >= 0.5 degrees          scan
    in between              UNKNOWN

We detect skew without OpenCV: render the page to greyscale, threshold
dark pixels, then for several candidate angles compute the projection
variance of dark pixels along rows. A higher variance = sharper rows =
better aligned. The peak variance angle is the page's actual rotation.

Strength: strong positive signal for "this is a scan", orthogonal to
all the content-based checks.

Weakness: rendering cost (similar to Op11/Op14). Synthetic test PDFs
generated by reportlab are perfectly aligned, so this option will say
SEARCHABLE on every one of them -- doesn't mean it's broken; it means
we don't have a real scan in the test set to fire on.

Engine: pypdfium2 + numpy.
"""
from __future__ import annotations

import math
import sys
from pathlib import Path

import numpy as np
import pypdfium2

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import Verdict, standalone_cli  # noqa: E402

NAME = "skew-detect"
RENDER_SCALE = 0.4
DARK_THRESHOLD = 100   # pixel <= this is "dark"
CANDIDATE_ANGLES = [round(a * 0.1, 1) for a in range(-30, 31)]  # -3..+3 degrees, 0.1° steps
NATIVE_MAX_ANGLE = 0.3
SCAN_MIN_ANGLE = 0.5


def _render_grey(page) -> np.ndarray:
    return np.asarray(page.render(scale=RENDER_SCALE, grayscale=True).to_pil(),
                      dtype=np.uint8)


def _best_angle(arr: np.ndarray) -> tuple[float, float]:
    """
    Return (angle_degrees, score) where score is the variance of the
    row-projection of dark pixels at that angle. Peak = best alignment.
    """
    dark = (arr <= DARK_THRESHOLD).astype(np.uint8)
    h, w = dark.shape
    cx = w / 2
    cy = h / 2
    y_idx, x_idx = np.indices(dark.shape)
    shifted_x = x_idx - cx
    shifted_y = y_idx - cy
    best = (0.0, -1.0)
    for ang in CANDIDATE_ANGLES:
        rad = math.radians(ang)
        # rotate inversely so projecting along rows = "would be horizontal" at angle ang
        new_y = shifted_y * math.cos(rad) - shifted_x * math.sin(rad) + cy
        rows = new_y.astype(np.int32)
        valid = (rows >= 0) & (rows < h)
        # sum dark pixels into rotated rows
        projection = np.bincount(rows[valid], weights=dark[valid], minlength=h)
        score = float(projection.var())
        if score > best[1]:
            best = (ang, score)
    return best


def _verdict_for_page(angle_deg: float) -> str:
    a = abs(angle_deg)
    if a <= NATIVE_MAX_ANGLE:
        return "SEARCHABLE"
    if a >= SCAN_MIN_ANGLE:
        return "OCR"
    return "UNKNOWN"


def evaluate(pdf_bytes: bytes, sampled: list[int]) -> Verdict:
    per_page: list[dict] = []
    pdf = pypdfium2.PdfDocument(pdf_bytes)
    try:
        for i in sampled:
            arr = _render_grey(pdf[i])
            angle, score = _best_angle(arr)
            per_page.append({
                "page": i,
                "skew_deg": angle,
                "score": round(score, 1),
                "verdict": _verdict_for_page(angle),
            })
    finally:
        pdf.close()

    if not per_page:
        return Verdict(NAME, "UNKNOWN", "no pages")
    threshold = math.floor(len(per_page) / 2) + 1
    ocr = sum(1 for p in per_page if p["verdict"] == "OCR")
    search = sum(1 for p in per_page if p["verdict"] == "SEARCHABLE")
    if ocr >= threshold:
        v = "OCR"
    elif search >= threshold:
        v = "SEARCHABLE"
    else:
        v = "UNKNOWN"
    return Verdict(NAME, v, f"OCR={ocr}, SEARCH={search}, ?={len(per_page)-ocr-search}", per_page)


if __name__ == "__main__":
    standalone_cli(evaluate, __doc__)
